import Head from "next/head";
import Extensions from "../components/Extensions/Index";
import Faq from "../components/Faq/Index";
import Features from "../components/Featured/Index";
import Footer from "../components/Footer/Footer";
import MainSection from "../components/MainSection";

export default function Home() {
  return (
    <div className="font-rubik  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection />
      <Features />
      <Extensions />
      <Faq />
      <Footer />
    </div>
  );
}
